config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "home#index"
  
  get 'auth/xero_oauth/callback', to: 'xero_oauth#callback'
  
  post :sync_invoices, to: "home#sync_invoices", as: :sync_invoices
  post :disconnect, to: "home#disconnect", as: :disconnect
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/invoice.rb
class Invoice < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  serialize :xero_token_set, Hash 
  
  has_many :invoices
  
  def connected_with_xero?
    !xero_token_set.empty?
  end
  
  def fetch_invoices_from_xero
    return unless connected_with_xero?
    
    xero_service = XeroService.new(xero_token_set)
    
    # Fetch invoices from each tenant
    xero_token_set["connections"].each do |connection|
      xero_service.fetch_invoices(connection["tenantId"]) do |fetched_invoices|
        create_or_update_invoices(fetched_invoices, connection["tenantId"])
      end
    end
  end
  
  def refresh_xero_token
    xero_service = XeroService.new(xero_token_set)
    self.xero_token_set = xero_service.refresh_token 
    
    self.save
  end
  
  private 
  
  def create_or_update_invoices(fetched_invoices, tenant_id)
    fetched_invoices.each do |invoice|
      self.invoices.where(xero_invoice_id: invoice.invoice_id).first_or_create(
        outstanding_amount: invoice.amount_due,
        total_amount: invoice.total,
        due_date: invoice.due_date,
        status: invoice.status,
        client_name: invoice.contact.name,
        contact_id: invoice.contact.contact_id,
        tenant_id: tenant_id
      )
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  helper_method :xero_client
  
  private 
  def xero_client
    @xero_client ||= XeroService.new.xero_client
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @invoices = current_user.invoices
    
    @page = params[:page] || 1
    
    if params[:tenant_id].present?
      @invoices = @invoices.where(tenant_id: params[:tenant_id])
    end
    
    @invoices = @invoices.page(params[:page])
  end
  
  def sync_invoices
    current_user.refresh_xero_token 
    
    current_user.fetch_invoices_from_xero
    
    flash.notice = "Successfully synced all invoices"
    
    redirect_to root_path
  end
  
  def disconnect
    current_user.xero_token_set = {}
    current_user.save!
    
    render :index
  end
end

app/controllers/xero_oauth_controller.rb
class XeroOauthController < ApplicationController 
  before_action :xero_client
  
  def callback 
    if params['code']
      @token_set = xero_client.get_token_set_from_callback(params)
      current_user.xero_token_set = @token_set if !@token_set["error"]
      current_user.xero_token_set['connections'] = xero_client.connections
      current_user.active_tenant_id = latest_connection(current_user.xero_token_set['connections'])
      current_user.save!
      
      SyncInvoices.perform_later current_user.id 
      
      flash.notice = "Successfully received Xero Token Set"
    else
      flash.notice = "Failed to received Xero Token Set"
    end
    
    redirect_to root_path
  end
  
  private
  def latest_connection(connections)
    if !connections.empty?
      connections.sort { |a,b|
        DateTime.parse(a['updatedDateUtc']) <=> DateTime.parse(b['updatedDateUtc'])
      }.first['tenantId']
    else
      nil
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def xero_authorization_url
    @xero_authorization_url ||= xero_client.authorization_url 
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<h1>Invoices</h1>

<turbo-frame id="invoice-list">
  <%= render "layouts/flash" %>
  <% if current_user.connected_with_xero? %>
    <div class="row mb-4">
      <div class="col-4">
        <%= form_tag "/", method: :get do %>
          <div class="form-group mb-2">
            <label for="tenant_id">Active Tenant</label>
            <%= select_tag "tenant_id", options_for_select(current_user.xero_token_set["connections"].pluck("tenantName", "tenantId"), selected: params[:tenant_id]), include_blank: "All", class: "form-select" %>
          </div>
          <div class="form-group">
            <%= submit_tag "View invoices", class: "btn btn-primary" %>
          </div>
        <% end %>
      </div>
      <div class="col-4 text-end offset-4 text-end">
        <%= form_tag sync_invoices_path do %>
          <%= submit_tag "Sync invoices", class: "btn btn-primary mb-4" %>
        <% end %>
        
        <%= form_tag disconnect_path do %>
          <%= submit_tag "Disconnect from Xero", class: "btn btn-danger" %>
        <% end %>
        
      </div>
    </div>
    
    <% if @invoices.present? %>
      <%= paginate @invoices, theme: 'bootstrap-5' %>
      <table class="table mt-3">
        <thead>
          <tr>
            <th>Invoice ID</th>
            <th>Client</th>
            <th>Outstanding amount</th>
            <th>Total amount</th>
            <th>Due date</th>
            <th>Status</th>
          </tr>
        </thead>
        <tbody>
          <% @invoices.each do |invoice| %>
            <tr>
              <td><%= invoice.xero_invoice_id %></td>
              <td><%= invoice.client_name %></td>
              <td><%= number_to_currency(invoice.outstanding_amount) %></td>
              <td><%= number_to_currency(invoice.total_amount) %></td>
              <td><%= invoice.due_date %></td>
              <td><%= invoice.status %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <%= paginate @invoices, theme: 'bootstrap-5' %>
    <% elsif !@invoices.nil? %>
      <h4 class="mt-4">No data. Refresh the page or sync again to see latest data.</h4>
    <% end %>
  <% else %>
    <%= link_to "Connect with Xero", xero_authorization_url, class: "btn btn-primary" %>
  <% end %>
</turbo-frame>

app/views/layouts/_flash.html.erb
<% if flash.notice %>
  <div class="alert alert-warning"><%= flash[:notice] %></div>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">Xero Integration App</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ms-auto">
        <li class="nav-item">
          <% if user_signed_in? %>
            <%= link_to "Logout", destroy_user_session_path, data: { turbo_method: :delete }, class: "nav-link" %>

          <% else %>
            <a class="nav-link active" aria-current="page" href="#">Sign In</a>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Xero Integration Test App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "layouts/navbar" %>
    <div class="container py-3">
      <%= yield %>
    </div>
  </body>
</html>